services:
  # Service Discovery (Eureka)
  discovery-service:
    build: ./microservices/discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=admin
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: ./microservices/api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - EUREKA_SERVER_URL=http://admin:admin@discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Contract Management Service
  contract-service:
    build: ./microservices/contract-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/legaldb
      - DB_USER=legaluser
      - DB_PASSWORD=legalpass
      - EUREKA_SERVER_URL=http://admin:admin@discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # LLM Processing Service
  llm-service:
    build: ./microservices/llm-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - LLAMA_BASE_URL=http://host.docker.internal:11434
      - EUREKA_SERVER_URL=http://admin:admin@discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: legaldb
      POSTGRES_USER: legaluser
      POSTGRES_PASSWORD: legalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U legaluser -d legaldb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - legalai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  legalai-network:
    driver: bridge