services:
  # 数据库
  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/library/postgres:15
    environment:
      POSTGRES_DB: legaldb
      POSTGRES_USER: legaluser
      POSTGRES_PASSWORD: legalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legalai-network

  # Redis 缓存
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/library/redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - legalai-network

  # LLaMA 服务器
  llama-server:
    image: registry.cn-hangzhou.aliyuncs.com/ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - llama_data:/root/.ollama
    networks:
      - legalai-network

volumes:
  postgres_data:
  llama_data:

networks:
  legalai-network:
    driver: bridge 