server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: contract-service
          uri: lb://contract-service
          predicates:
            - Path=/api/contracts/**
          filters:
            - name: CircuitBreaker
              args:
                name: contractCircuitBreaker
                fallbackUri: forward:/fallback/contract
        
        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/api/llm/**
          filters:
            - name: CircuitBreaker
              args:
                name: llmCircuitBreaker
                fallbackUri: forward:/fallback/llm
        
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
          filters:
            - name: CircuitBreaker
              args:
                name: fileCircuitBreaker
                fallbackUri: forward:/fallback/file
        
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always 