global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'contract-service'
    static_configs:
      - targets: ['contract-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'eureka'
    static_configs:
      - targets: ['discovery-service:8761']
    metrics_path: '/actuator/prometheus' 