server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      routes:
        - id: contract-service
          uri: lb://CONTRACT-SERVICE
          predicates:
            - Path=/api/contracts/**
          filters:
            - ServiceAuthenticationFilter
            - RewritePath=/api/contracts/(?<segment>.*), /api/contracts/${segment}
        
        - id: llm-service
          uri: lb://LLM-SERVICE
          predicates:
            - Path=/api/llm/**
          filters:
            - ServiceAuthenticationFilter
            - RewritePath=/api/llm/(?<segment>.*), /api/llm/${segment}
        
        - id: auth-service-internal
          uri: lb://API-GATEWAY
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyThatMustBeAtLeast256BitsForHS256AlgorithmToWork}
  expiration: ${JWT_EXPIRATION:86400000}

service:
  api:
    key: ${SERVICE_API_KEY:defaultServiceApiKeyForInternalCommunication}

logging:
  level:
    root: INFO
    com.example.legalai: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"