spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  
  cloud:
    gateway:
      routes:
        - id: contract-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/contracts/**
        - id: llm-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/llm/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "chrome-extension://*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

logging:
  level:
    com.example.legalai: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway