server:
  port: 8082

spring:
  application:
    name: llm-service
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
  cloud:
    config:
      uri: http://config-service:8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

llama:
  base-url: ${LLAMA_BASE_URL:http://localhost:11434}
  model: ${LLAMA_MODEL:llama3}
  timeout: ${LLAMA_TIMEOUT:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.legalai.llm: DEBUG
    org.springframework.web: DEBUG 