spring:
  application:
    name: llm-service
  profiles:
    active: dev
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      
server:
  port: 8082

logging:
  level:
    com.example.legalai: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

llm:
  provider: 
    base-url: http://localhost:11434
    timeout: 30s
  cache:
    ttl: 24h